#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

DRUPAL_SETTINGS=$OPENSHIFT_REPO_DIR/sites/default/settings.php

# check and set the symlink for files dir
if [ ! -d "$OPENSHIFT_REPO_DIR/sites/default/files" ]; then
    echo !!! files symlink does NOT exist - creating symlink...
    #mkdir $OPENSHIFT_DATA_DIR/sites
    echo !!! created files directory - creating symlink...
    ln -s $OPENSHIFT_DATA_DIR/files $OPENSHIFT_REPO_DIR/sites/default/files
    echo !!! created symlink - setting permissions on directory...
    chmod -R 0755 $OPENSHIFT_DATA_DIR/files
    echo !!! permissions have been set on files directory!
else
    echo !!! sites directory already exists - skipping symlink...
fi

# check and set the symlink for files dir
if [ ! -d "$OPENSHIFT_REPO_DIR/sites/default/private" ]; then
    echo !!! private symlink does NOT exist - creating symlink...
    #mkdir $OPENSHIFT_DATA_DIR/sites
    echo !!! created private directory - creating symlink...
    ln -s $OPENSHIFT_DATA_DIR/private $OPENSHIFT_REPO_DIR/sites/default/private
    echo !!! created symlink - setting permissions on directory...
    chmod -R 0755 $OPENSHIFT_DATA_DIR/private
    echo !!! permissions have been set on private directory!
else
    echo !!! sites directory already exists - skipping symlink...
fi

cat > $DRUPAL_SETTINGS << EOF
<?php

\$update_free_access = FALSE;
\$drupal_hash_salt = 'fbKO2wsCjqm44RwY5UgVsajejcYS7pTR4HvYiuc7lJ8';

ini_set('session.gc_probability', 1);
ini_set('session.gc_divisor', 100);

ini_set('session.gc_maxlifetime', 200000);

ini_set('session.cookie_lifetime', 2000000);

\$conf['404_fast_paths_exclude'] = '/\/(?:styles)\//';
\$conf['404_fast_paths'] = '/\.(?:txt|png|gif|jpe?g|css|js|ico|swf|flv|cgi|bat|pl|dll|exe|asp)$/i';
\$conf['404_fast_html'] = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL "@path" was not found on this server.</p></body></html>';

\$databases = array (
  'default' => 
  array (
    'default' => 
    array (
      'database' => getenv('OPENSHIFT_APP_NAME'),
      'username' => getenv('OPENSHIFT_MYSQL_DB_USERNAME'),
      'password' => getenv('OPENSHIFT_MYSQL_DB_PASSWORD'),
      'host' => getenv('OPENSHIFT_MYSQL_DB_HOST'),
      'port' => getenv('OPENSHIFT_MYSQL_DB_PORT'),
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
);
EOF

chmod u+w $DRUPAL_SETTINGS $OPENSHIFT_REPO_DIR/sites/default

cp $OPENSHIFT_DATA_DIR/.htaccess $OPENSHIFT_REPO_DIR/.htaccess
