<?php
if (!defined('ON_SUCCESS_URL')) define('ON_SUCCESS_URL', 'https://cityfruit.org/clickandpledge/success.php');
if (!defined('ON_DECLINE_URL')) define('ON_DECLINE_URL', 'https://cityfruit.org/clickandpledge/decline.php');
if (!defined('ON_ERROR_URL')) define('ON_ERROR_URL', 'https://cityfruit.org/clickandpledge/error.php');
if (!defined('DEFAULT_SF_CAMPAIGN')) define('DEFAULT_SF_CAMPAIGN', 'Website Donation');
if (!defined('CNP_ACCOUNT_GUID')) define('CNP_ACCOUNT_GUID', 'a4b4b94a-fb2b-4bc7-be81-c92b398566b1');
if (!defined('CNP_ACCOUNT_ID')) define('CNP_ACCOUNT_ID', '19933');
if (!defined('CNP_WID')) define('CNP_WID', '94336');
if (!defined('CNP_REF_ID')) define('CNP_REF_ID', 'donation');
if (!defined('CNP_TRACKER')) define('CNP_TRACKER', 'FaaS-cityfruit-donation');
if (!defined('CNP_SEND_RECEIPT')) define('CNP_SEND_RECEIPT', 'false');
if (!defined('CNP_ORDER_MODE')) define('CNP_ORDER_MODE', 'Production');
if (!defined('CNP_TRANSACTION_TYPE')) define('CNP_TRANSACTION_TYPE', 'Payment');
if (!defined('CNP_DECIMAL_MARK')) define('CNP_DECIMAL_MARK', 'US');
if (!defined('ERROR_EMAIL_TO')) define('ERROR_EMAIL_TO', 'i8flan@gmail.com');
if (!defined('ERROR_EMAIL_SUBJECT')) define('ERROR_EMAIL_SUBJECT', 'City Fruit Donation Page Error');
?>
